version: '3.1'

services:

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dev_DB
      MARIADB_USER: dev
      MARIADB_PASSWORD: p
    networks:
      - dev-network

  my-php:
    container_name: my-php
    build:
      context: .
      dockerfile: ./php-Dockerfile
    image: my/php:latest
    # Allow start X window
    privileged: true
    ports:
      # Apache
      - "127.0.0.1:8080:80"
      # Others, pre-configured
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8010:8010"
      - "127.0.0.1:8100:8100"
    volumes:
      # mount X11 folder, needed for Electro
      - /tmp/.X11-unix:/tmp/.X11-unix
      # example: mount home projects into /builder (home of builder user)
      - ~/Documents/projets/:/builder/projects
    environment:
      DISPLAY: $DISPLAY
    # WARNING: Do not override command !
      # command: nothing
    # keep container running
    tty: true
    networks:
      - dev-network
    depends_on:
      mariadb:
        condition: service_started

  my-node:
    container_name: my-node
    build:
      context: .
      dockerfile: ./node-Dockerfile
    image: my/node:latest
    # Allow start X window
    privileged: true
    ports:
      # Nodes
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3001"
      - "127.0.0.1:3010:3010"
      - "127.0.0.1:3100:3100"
    volumes:
      # mount X11 folder, needed for Electro
      - /tmp/.X11-unix:/tmp/.X11-unix
      # example: mount home projects into /builder (home of builder user)
      - ~/Documents/projets/:/builder/projects
    environment:
      DISPLAY: $DISPLAY
    # WARNING: Do not override command !
      # command: nothing
    # keep container running
    tty: true
    networks:
      - dev-network
    depends_on:
      mariadb:
        condition: service_started

networks:
  dev-network:
    external: false
    name: dev-network

