version: '3.1'

services:

  mysql:
    container_name: oclock-mysql
    image: pimarie/oclock:mysql
    build:
      context: .
      dockerfile_inline: 
        FROM mariadb:latest
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: oclock_DB
      MARIADB_USER: oclock 
      MARIADB_PASSWORD: oclock_password
