version: "3.1"

services:

  postgres:
    container_name: oclock-postgres
    image: pimarie/oclock:postgres
    build:
      context: .
      dockerfile_inline: 
        FROM postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: oclock_DB
      POSTGRES_USER: oclock
