CREATE DATABASE IF NOT EXISTS `wordpress`;

CREATE USER 'wordpress'@'%' IDENTIFIED BY 'p';
GRANT USAGE ON *.* TO 'wordpress'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `wordpress`.* TO 'wordpress'@'%'; 