CREATE DATABASE IF NOT EXISTS `dev_DB`;

CREATE USER 'dev'@'%' IDENTIFIED BY 'p';
GRANT USAGE ON *.* TO 'dev'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `dev_DB`.* TO 'dev'@'%'; 