version: '3.1'

services:

  node:
    container_name: node
    image: pimarie/node:2024-01-08
    ports:
      # Node
      - "127.0.0.1:8000:8000"
    command: bash
    tty: true
    networks:
      - dev-network
    volumes:
      # mount home projects into node
      - /home/pirik/Documents/projets/:/home/node/

networks:
  dev-network:
    # use existing network
    external: true
    name: dev-network
