version: '3.1'

services:

  electron:
    container_name: electron
    image: pimarie/manjaro:webdev-electron
    privileged: true
    ports:
      # MySQL
      - "127.0.0.1:3306:3306"
      # Apache
      - "127.0.0.1:8080:80"
      # Others
      - "127.0.0.1:8000:8000"
    volumes:
      # mount X11 folder
      - /tmp/.X11-unix:/tmp/.X11-unix
      # mount home projects into /builder (home of builder user)
      - /home/pirik/Documents/projets/:/builder/projects
      - /home/pirik/Documents/oclock/:/builder/oclock
    environment:
      DISPLAY: $DISPLAY
    # configure container and run apache and mariadb
    command: /root/setup.sh
    tty: true

networks:
  dev-network:
    # use existing network
    external: true
    name: dev-network