version: '3.1'

services:

  lamp:
    container_name: manjaro-webdev
    image: pimarie/manjaro:webdev
    ports:
      # MySQL
      - "127.0.0.1:3306:3306"
      # Apache
      - "127.0.0.1:8080:80"
      # Autre : node, etc.
      - "127.0.0.1:8000:8000"
    # start apache and MySQL
    command: /root/start-lamp.sh
    tty: true
    networks:
      - dev-network
    volumes:
      # mount home projects into node
      - /home/pirik/Documents/projets/:/home/node/
      # apache home web dev : http://localhost:8080/~dev
      #  - ./:/home/dev/www/

networks:
  dev-network:
    # use existing network
    external: true
    name: dev-network
