version: '3.1'

services:

  electron:
    container_name: electron-from-scratch
    # image: pimarie/manjaro:webdev-electron
    # build: .
    image: electron-from-scratch:latest
    privileged: true
    # ports:
      # MySQL
      # - "127.0.0.1:3306:3306"
      # Apache
      # - "127.0.0.1:8080:80"
      # Others
      # - "127.0.0.1:8000:8000"
    volumes:
      # mount X11 folder
      - /tmp/.X11-unix:/tmp/.X11-unix
      # mount home projects into /builder (home of builder user)
      # - ~/Documents/projets/:/builder/projects
      # - ~/Documents/oclock/:/builder/oclock
    environment:
      DISPLAY: $DISPLAY
    # WARNING: Do not override command !
    command: /usr/local/bin/start-up.sh
    # keep container running
    tty: true

networks:
  dev-network:
    # use existing network
    external: true
    name: dev-network

